// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVoe4ItK-H6DZ9Cd4PPLeYoMxam7QI2CU',
    appId: '1:249872555742:web:06e32166d0301a8bceec4f',
    messagingSenderId: '249872555742',
    projectId: 'flutter-task-4da09',
    authDomain: 'flutter-task-4da09.firebaseapp.com',
    storageBucket: 'flutter-task-4da09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9a5GFZWzDtcYtX7jeIMSHTHubkkGogIc',
    appId: '1:249872555742:android:79faff2fa223bca3ceec4f',
    messagingSenderId: '249872555742',
    projectId: 'flutter-task-4da09',
    storageBucket: 'flutter-task-4da09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe-nZVm8r-hDGIndSVWEss7EPqYOXSEns',
    appId: '1:249872555742:ios:561faa3d2a25dc36ceec4f',
    messagingSenderId: '249872555742',
    projectId: 'flutter-task-4da09',
    storageBucket: 'flutter-task-4da09.appspot.com',
    iosClientId: '249872555742-o2il2kie9fgktcukkuu9ahdaregvesdo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe-nZVm8r-hDGIndSVWEss7EPqYOXSEns',
    appId: '1:249872555742:ios:561faa3d2a25dc36ceec4f',
    messagingSenderId: '249872555742',
    projectId: 'flutter-task-4da09',
    storageBucket: 'flutter-task-4da09.appspot.com',
    iosClientId: '249872555742-o2il2kie9fgktcukkuu9ahdaregvesdo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTask',
  );
}
